# Generated by Django 4.0.5 on 2022-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('icon', models.CharField(choices=[('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/bread-red.png', 'piece of bread'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/burger-4.png', 'burger'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/salad.png', 'vegetables'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/fish-red.png', 'fish'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/desert-red.png', 'pie'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/soup-red.png', 'soup')], max_length=100, verbose_name='Иконка')),
                ('icon2', models.CharField(choices=[('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/bread-red.png', 'piece of bread'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/burger-4.png', 'burger'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/salad.png', 'vegetables'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/fish-red.png', 'fish'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/desert-red.png', 'pie'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/soup-red.png', 'soup')], max_length=100, verbose_name='Иконка2')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
