# Generated by Django 4.0.5 on 2022-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/bread-red.png', 'piece of bread'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/burger-4.png', 'burger'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/salad.png', 'vegetables'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/fish-red.png', 'fish'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/desert-red.png', 'pie'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/soup-red.png', 'soup')], help_text='Желательно выбирать одинаковые иконки', max_length=100, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon2',
            field=models.CharField(choices=[('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/bread-white.png', 'piece of bread'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/sandwich-white.png', 'burger'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/salad-white.png', 'vegetables'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/fish-white.png', 'fish'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/desert-write.png', 'pie'), ('https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2020/05/soup.png', 'soup')], help_text='Желательно выбирать одинаковые иконки', max_length=100, verbose_name='Иконка2'),
        ),
    ]
