# Generated by Django 4.0.5 on 2022-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_category_options_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='https://radiustheme.com/demo/wordpress/themes/ranna/wp-content/uploads/2019/10/img_6.png', upload_to='category_images/', verbose_name='Фото'),
        ),
    ]
