# Generated by Django 4.0.5 on 2022-06-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_tag_alter_category_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.CharField(help_text='Пишите рецепт через запятую', max_length=550, verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_five',
            field=models.TextField(blank=True, null=True, verbose_name='Шаг 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_four',
            field=models.TextField(blank=True, null=True, verbose_name='Шаг 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_one',
            field=models.TextField(verbose_name='Шаг 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_three',
            field=models.TextField(verbose_name='Шаг 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_two',
            field=models.TextField(verbose_name='Шаг 2'),
        ),
    ]
