# Generated by Django 4.0.5 on 2022-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(help_text='Введите ссылку на рекламу', max_length=255, verbose_name='Ссылка'),
        ),
    ]
