# Generated by Django 4.0.5 on 2022-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_advertisement_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='address',
            field=models.CharField(help_text='Введите ссылку на вашу социальную сеть', max_length=255, verbose_name='Ссылка'),
        ),
    ]
