# Generated by Django 4.0.5 on 2022-06-20 05:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_network_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('about', 'about')], default='about', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Фото')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'О вас',
                'verbose_name_plural': 'О вас',
            },
        ),
    ]
